WebApplication1/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;

namespace WebApplication1.Models
{
    public class CartIndexViewModel
    {
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebApplication1/Models/PagingInfo.cs
using System;

namespace WebApplication1.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPage
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }


    }
}

WebApplication1/Models/ProductListViewModel.cs
using SportsStore.Domain.Entities;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

WebApplication1/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        public CartController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { cart = cart, ReturnUrl = returnUrl });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                // GetCart().AddItem(product, 1);
                cart.AddItem(product, 1);

            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                // GetCart().RemoveItem(product);
                cart.RemoveItem(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //private Cart GetCart()  I COMMENTED THIS AFTER I DID MY CARTINDEXVIEWMODEL AND POSTED IT IN GLOBAL.ASAX.CS
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)d
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}

WebApplication1/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }


        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.products.Select(x => x.Category).Distinct().OrderBy(x => x);
            return PartialView(categories);
        }

    }
}

WebApplication1/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        private IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository productRepository)
        {
            repository = productRepository;
        }

        //public ViewResult List(int page = 1)
        //{
        //    return View(repository.products.OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize));
        //}

        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.products.Where(p => category == null || p.Category == category).
                OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.products.Count() : repository.products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

    }
}

WebApplication1/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails

@{ 
    ViewBag.Title = "SportsStore: Checkout";
}

<h2>Check out now</h2>
<p>Please enter your details and we'll ship it right away</p>
@using (Html.BeginForm())
{
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control"})
    </div>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control"})
            </div>
        }
    }

    @*<h3>Address</h3>
    <div class="form-group">
        <label>Line1:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Line2</label>
        @Html.TextBoxFor(x => x.Line2, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Line3</label>
        @Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>State</label>
        @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Zip</label>
        @Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Country</label>
        @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
    </div>*@

    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Gift wrap things here
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete Order" />
    </div>
}

WebApplication1/Views/Cart/Index.cshtml
@model WebApplication1.Models.CartIndexViewModel
@{ 
    ViewBag.Title = "Sports Store: Your cart";
}

<style>
    #cartTable td {vertical-align: middle;}

</style>

<h2>Your Cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove"/>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout Now", "Checkout", null, new { @class = "btn btn-primary"})
</div>

WebApplication1/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, new {@class = "btn btn-default navbar-btn"})
</div>
<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

WebApplication1/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-block btn-default btn-lg"})
@foreach (var link in Model)
{
    @Html.RouteLink(link, new { controller = "Product", action = "List", category = link, page = 1}, 
    new { @class = "btn btn-block btn-default btn-lg" + (link == ViewBag.SelectedCategory ? " btn-primary" : "" )})

}

WebApplication1/Views/Product/List.cshtml
@*@using SportsStore.Domain.Entities*@
@model WebApplication1.Models.ProductListViewModel


@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
   @Html.Partial("ProductSummary", p)
}
<div class="pager">
    @using WebApplication1.HtmlHelpers
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory}))
</div>

WebApplication1/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to the cart"/>
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title </title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
          @Html.Action("Menu", "Nav")
        </div>
    <div class="col-xs-8">
        @RenderBody()
    </div>
    </div>
</body>
</html>